
insert into homework (name, description) values ('Math','Task 1, 2');
insert into homework (name, description) values ('Physics','Task 3, 4');
insert into homework (name, description) values ('Chemistry','Task 5, 6');
insert into homework (name, description) values ('Information support','Task 7, 8');
insert into homework (name, description) values ('English','Task 9, 10');
insert into homework (name, description) values ('Rosina', 'tellus semper interdum mauris ullamcorper purus sit amet nulla quisque');
insert into homework (name, description) values ('Lucy', 'in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis');
insert into homework (name, description) values ('Germain', 'erat nulla tempus vivamus in felis eu sapien cursus vestibulum');
insert into homework (name, description) values ('Ofelia', 'donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis');
insert into homework (name, description) values ('Delilah', 'ac neque duis bibendum morbi non quam nec dui luctus');
insert into homework (name, description) values ('Erich', 'ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque');
insert into homework (name, description) values ('Bil', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada');
insert into homework (name, description) values ('Faustina', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
insert into homework (name, description) values ('Val', 'curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus');
insert into homework (name, description) values ('Sigismundo', 'amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis');
insert into homework (name, description) values ('Ashley', 'quam a odio in hac habitasse platea dictumst maecenas ut massa quis');
insert into homework (name, description) values ('Marlee', 'diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis');
insert into homework (name, description) values ('Lyndsay', 'consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante');
insert into homework (name, description) values ('Keary', 'justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum');
insert into homework (name, description) values ('Gun', 'turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate');
